uri: "http://downloads.sourceforge.net/project/pkgconfiglite/0.28-1/pkg-config-lite-0.28-1.tar.gz"
hash: "21b76ec4e115ee30f9b3077a2506e48e8b837332ed4d30c9776502e69c6a29e5"
name: "pkgconfiglite"
version: "0.28-1"
file: "pkg-config-lite-0.28-1.tar.gz"
build:
  :cross: "cd $EIR_PKGCONFIGLITE_SOURCE && touch Makefile.in && touch */Makefile.in && cd $EIR_PKGCONFIGLITE_BUILD && $EIR_PKGCONFIGLITE_SOURCE/configure --prefix=$EIR_CROSS_TOOLCHAIN_PREFIX --host=$EIR_TARGET --disable-dependency-tracking --with-pc-path=$EIR_TOOLCHAIN_PREFIX/lib64/pkgconfig:$EIR_TOOLCHAIN_PREFIX/share/pkgconfig && make && make install"
